/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Audit */
        post: operations["create_audit_v1_audits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audits/{audit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit */
        get: operations["get_audit_v1_audits__audit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audits/{audit_id}/re-audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re Audit */
        post: operations["re_audit_v1_audits__audit_id__re_audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_v1_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Atomicity
         * @enum {string}
         */
        Atomicity: "atomic" | "compound";
        /**
         * AuditLanguage
         * @enum {string}
         */
        AuditLanguage: "en" | "sk";
        /** AuditResult */
        AuditResult: {
            /** Claims */
            claims: components["schemas"]["ClaimResult"][];
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Events */
            events: components["schemas"]["EventResult"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input Text */
            input_text: string;
            language: components["schemas"]["AuditLanguage"];
            /** Model Manifest */
            model_manifest: {
                [key: string]: unknown;
            };
            /** Normalization Version */
            normalization_version: string;
            /** Pipeline Version */
            pipeline_version: string;
            /** Re Audit Of Id */
            re_audit_of_id: string | null;
            /** Safe Error Code */
            safe_error_code: string | null;
            /** Scoring Version */
            scoring_version: string;
            source_type: components["schemas"]["AuditSourceType"];
            /** Started At */
            started_at: string | null;
            state: components["schemas"]["AuditState"];
        };
        /**
         * AuditSourceType
         * @enum {string}
         */
        AuditSourceType: "pasted_text";
        /**
         * AuditState
         * @enum {string}
         */
        AuditState: "queued" | "running" | "succeeded" | "partially_succeeded" | "failed" | "cancel_requested" | "cancelled";
        /** ClaimResult */
        ClaimResult: {
            atomicity: components["schemas"]["Atomicity"];
            /** End Offset */
            end_offset: number;
            /** Exact Text */
            exact_text: string;
            /** Extraction Confidence */
            extraction_confidence: number;
            /** Findings */
            findings: components["schemas"]["FindingResult"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Normalized Text */
            normalized_text: string;
            /** Ordinal */
            ordinal: number;
            primary_type: components["schemas"]["ClaimType"] | null;
            /** Risk Components */
            risk_components: components["schemas"]["RiskComponentResult"][];
            /** Risk Score */
            risk_score: number | null;
            /** Secondary Types */
            secondary_types: string[];
            /** Start Offset */
            start_offset: number;
            status: components["schemas"]["ClaimStatus"] | null;
            /** Suggested Revisions */
            suggested_revisions: components["schemas"]["RevisionResult"][];
            verifiability: components["schemas"]["Verifiability"];
        };
        /**
         * ClaimStatus
         * @enum {string}
         */
        ClaimStatus: "low_risk" | "review_recommended" | "evidence_needed" | "internally_inconsistent" | "overstated" | "not_verifiable";
        /**
         * ClaimType
         * @enum {string}
         */
        ClaimType: "factual" | "causal" | "numerical" | "comparative" | "definitional" | "recommendation" | "other";
        /** CreateAuditRequest */
        CreateAuditRequest: {
            language: components["schemas"]["AuditLanguage"];
            /** Text */
            text: string;
        };
        /** DependencyResponse */
        DependencyResponse: {
            /** Action */
            action?: string | null;
            /** Ready */
            ready: boolean;
            /** Required */
            required: boolean;
            /** State */
            state: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /** EventResult */
        EventResult: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Event Type */
            event_type: string;
            /** Redacted Payload */
            redacted_payload: {
                [key: string]: unknown;
            };
            /** Sequence */
            sequence: number;
            /** Stage */
            stage: string;
            /** Status */
            status: string;
        };
        /** FindingResult */
        FindingResult: {
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Finding Type */
            finding_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Prompt Version */
            prompt_version: string | null;
            /** Rule Version */
            rule_version: string | null;
            severity: components["schemas"]["FindingSeverity"];
            source_kind: components["schemas"]["FindingSource"];
        };
        /**
         * FindingSeverity
         * @enum {string}
         */
        FindingSeverity: "info" | "low" | "moderate" | "high" | "critical";
        /**
         * FindingSource
         * @enum {string}
         */
        FindingSource: "deterministic" | "model_assisted";
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Dependencies */
            dependencies: {
                [key: string]: components["schemas"]["DependencyResponse"];
            };
            /** Status */
            status: string;
        };
        /** RevisionResult */
        RevisionResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            language: components["schemas"]["AuditLanguage"];
            /** Model Version */
            model_version: string;
            /** Prompt Version */
            prompt_version: string;
            /** Rationale */
            rationale: string;
            /** Replacement Text */
            replacement_text: string;
            validation_status: components["schemas"]["RevisionValidationStatus"];
        };
        /**
         * RevisionValidationStatus
         * @enum {string}
         */
        RevisionValidationStatus: "pending" | "valid" | "invalid";
        /** RiskComponentResult */
        RiskComponentResult: {
            /** Component Type */
            component_type: string;
            /** Explanation Message Key */
            explanation_message_key: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Points */
            points: number;
            /** Raw Value */
            raw_value: {
                [key: string]: unknown;
            };
            /** Scoring Version */
            scoring_version: string;
        };
        /**
         * Verifiability
         * @enum {string}
         */
        Verifiability: "externally_verifiable" | "internally_verifiable" | "not_verifiable";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_audit_v1_audits_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAuditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResult"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Idempotency key conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A required local service or model is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_audit_v1_audits__audit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResult"];
                };
            };
            /** @description Audit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    re_audit_v1_audits__audit_id__re_audit_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResult"];
                };
            };
            /** @description Source audit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Idempotency key conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A required local service or model is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    readiness_v1_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
